### ISSUE TITLE
json filter fails to serialize any content with a relationship

### ISSUE THREAD

**Issue by asprouse** [webhook/webhook#47]
According to the documentation using Webhook it should be possible generate quick static [JSON endpoints](http://www.webhook.com/docs/common-patterns/#quicky_json_jsonp_api). This pattern works like a charm until a relationship is added and then the filter will cause the following error:
```
TypeError: Converting circular structure to JSON
```
This problem could be avoided by creating a de-cycle filter or option on the existing json filter. There is an [existing public domain de-cycle algorithm](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js) written by Crockford which could be used. This algorithm replaces already seen objects with a refrence object containing a [JSONPath](http://GOESSNER.net/articles/JsonPath/) which can be used by the consumer to reestablish the circular references after deserialization.

The issue with the decycle filter is that it will leave in other potentially unwanted objects in the reverse relation. A the solution to this would be to not serialize reverse relations. Figuring this out in the template layer might be a bit tricky without attaching metadata to the object to indicate the reverse relationship. A potentially simpler solution would be to assume that any property with a circular reference is indeed a reverse relation. Limiting the depth of recursion while serializing might be another option.

Maybe I am missing something, since this functionality is a listed in the "common pattern" section of the documentation, but if I am not this should be supported without having to resort to manually serializing in swig.

**Comment by snide** [comment]
Noted. We'll look into this soon. Moving it to the generate repo, where the bug occurs. https://github.com/webhook/webhook-generate/issues/31
