### ISSUE TITLE
imageCrop 'auto' parameter stopped working

### ISSUE THREAD

**Issue by DanDias** [webhook/webhook#49]
I have an images in a content type that are cropped to 300px tall. It used to work with the below syntax but is now showing up as a broken link. The google content URL reports a 500 error. http://www.mindcrit.com/blog/ is where this is happening. Works fine if I supply two numbers for parameters.

Sample Syntax:
```twig
<img class="image featured" src="{% if post.cover %}{{post.cover|imageCrop('auto',300)}}{% else %}{% endif %}" alt="Cover Image for: {{post.name}}" />
```

**Comment by snide** [comment]
Hmm. This was never in our docs and no code has changed around images for a few months. What do you expect "auto" to do? A crop is a defined size.

**Comment by snide** [comment]
Hmm. I'll run some tests on this over the weekend. None of the image code has changed in a bit though.

**Comment by LtSquigs** [comment]
Put in a quick fix for this, googles backend stopped accepting a null parameter for one of the two parameters, so im passing 0 instead (which seems to evaluate to being a no-op)
